/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package encryption_tasks;

import Double_Transposition_tecnique.double_transporation_encryption;
import ceaser_technique.ceaser_encryption;
import one_time_pad_technique.one_time_pad_encryption;






/**
 *
 * @author Abuelhassan
 */
public class Choose_the_way extends javax.swing.JFrame {

    /**
     * Creates new form ceaser_encryption
     */
    public Choose_the_way() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        doubletansposition = new javax.swing.JButton();
        ceaser = new javax.swing.JButton();
        onetimepadding = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Choose the way ");
        setResizable(false);

        jPanel1.setLayout(null);

        doubletansposition.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        doubletansposition.setText("Double Transposition Technique");
        doubletansposition.setFocusPainted(false);
        doubletansposition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doubletanspositionActionPerformed(evt);
            }
        });
        jPanel1.add(doubletansposition);
        doubletansposition.setBounds(20, 180, 330, 60);

        ceaser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ceaser.setText("Ceaser Technique");
        ceaser.setFocusPainted(false);
        ceaser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceaserActionPerformed(evt);
            }
        });
        jPanel1.add(ceaser);
        ceaser.setBounds(20, 90, 330, 60);

        onetimepadding.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        onetimepadding.setText("One Time Padding Technique");
        onetimepadding.setFocusPainted(false);
        onetimepadding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onetimepaddingActionPerformed(evt);
            }
        });
        jPanel1.add(onetimepadding);
        onetimepadding.setBounds(20, 270, 330, 60);

        exit.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        exit.setText("Exit");
        exit.setFocusPainted(false);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit);
        exit.setBounds(20, 360, 330, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("Choose the way to encrypt");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 20, 490, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/encryption_tasks/ZenMate.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 590, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doubletanspositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doubletanspositionActionPerformed
        double_transporation_encryption dte = new double_transporation_encryption();
        dte.setSize(580, 463);
        dte.setLocation(400, 150);
        dte.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_doubletanspositionActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void ceaserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceaserActionPerformed
        ceaser_encryption ce = new ceaser_encryption();
        ce.setSize(580, 463);
        ce.setLocation(400, 150);
        ce.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ceaserActionPerformed

    private void onetimepaddingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onetimepaddingActionPerformed
        one_time_pad_encryption on = new one_time_pad_encryption();
        on.setSize(580, 463);
        on.setLocation(400, 150);
        on.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_onetimepaddingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choose_the_way.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choose_the_way.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choose_the_way.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choose_the_way.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Choose_the_way().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ceaser;
    private javax.swing.JButton doubletansposition;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton onetimepadding;
    // End of variables declaration//GEN-END:variables
}
